# Generated by Django 3.1.6 on 2021-02-27 06:40

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='', validators=[accounts.validators.validate_size]),
        ),
    ]
